/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bottom: typeof import('./components/Game/Bottom.vue')['default']
    CpuMessage: typeof import('./components/Game/CpuMessage.vue')['default']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Main: typeof import('./components/Game/Main.vue')['default']
    Panel: typeof import('./components/Game/Panel.vue')['default']
    Radio: typeof import('./components/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Score: typeof import('./components/Game/Score.vue')['default']
    SettingStart: typeof import('./components/SettingStart.vue')['default']
    ShiritoiArea: typeof import('./components/Game/ShiritoiArea.vue')['default']
    Stage: typeof import('./components/Game/Stage.vue')['default']
    TimeLimit: typeof import('./components/Game/TimeLimit.vue')['default']
  }
}
